# 配置端口
server:
  port: 5555

spring:
  # 配置redis
  redis:
    timeout: 10000ms
    host: 110.40.236.91
    port: 6379
    database: 0
    password: 123456
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5


  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: gongxiwu
    hikari:
      # 连接池名
      pool-name: DataHikarCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间,默认10min
      idle-timeout: 18000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间,0表示永久存活,默认30min
      max-lifetime: 1800000
      # 连接超时时间,默认30s
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1




# 配置mybatis-plus
mybatis-plus:
  type-aliases-package: com.gong.pojo
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
# 日志打印 mybatis sql(方法接口所在的包,不是Mapper.xml的包)
logging:
  level:
    com.gong.mapper: debug

jwt:
  # jwt存储的请求头
  tokenHeader: Authorization
  # jwt加解密使用的秘钥
  secret: yeb-secret
  # jwt的超期限时间
  expiration: 604800
  # jwt负载中拿到开头
  tokenHead: Bearer
